#include <iostream>
#include "xtor_calculator.hh"


//main function
//In simulation HW top is the entry point, so we need to amke a call for C++ main from there. That's why we declare this function as extern "C" ifdef SIMULATOR
//in case of simulator compilation, we need to declare the function as extern "C" because there is a conflict of 2 mains, 1st main which you declared in C++ and 2nd main which gets auto generated by VCS simulator for sv files.
//in case of emulation, we have only one main, which we declare it manually here

#ifndef SIMULATOR
int send_traffic();
int main() {
    return send_traffic();
}
#endif
#ifdef SIMULATOR
extern "C" {
#endif

void send_traffic() {
    //object declaration
    xtor_calculator calculator1;

    std::cout << "\n" << std::string(50, '=') << std::endl;
    std::cout << "  [inside Main]Calculator DPI Test - Software Driven" << std::endl;
    std::cout << std::string(50, '=') << std::endl;
    
    int A=10, B=5, op=0, rst=0;
    
    // Reset sequence
    calculator1.traffic(A, B, op, 1); // reset high
    calculator1.traffic(A, B, op, 0); // reset low
    
    std::cout << "\n" << std::string(50, '=') << std::endl;
    std::cout << "  [inside Main]Running Arithmetic Operations" << std::endl;
    std::cout << std::string(50, '=') << std::endl;
    
    // Test all operations
    for (op=1; op<=4; op++) {
        calculator1.traffic(A, B, op, rst); // reset low
    }
    
    std::cout << "\n" << std::string(50, '=') << std::endl;
    std::cout << "  [inside Main]Test Completed Successfully!" << std::endl;
    std::cout << std::string(50, '=') << std::endl << std::endl;
    
    // Call callback to notify completion
    callback_sv();
}
#ifdef SIMULATOR
}
#endif